name: Publish to PyPI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine  # Install the necessary packaging tools

      - name: Build the distribution
        run: |
          python setup.py sdist bdist_wheel  # Build the source distribution and wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"  # Set username to PyPI token identifier
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}  # Use the secret for PyPI token
        run: |
          python -m pip install --upgrade twine
          twine upload dist/*  # Upload the distribution to PyPI
